title: ひかりの実験室
copyright: © 2023 Hikari
author: ひかり
future: true
url: "https://www.hikari-dev.com"
lang: ja_JP
description: >-
  Hikari's personal website that is written information technology.
github_username: himeyama

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    archives: '/archives'
    category: '/category/:name/'

plugins:
  - jekyll-coffeescript
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
